/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/beercannew.glb -o src/components/BeerCan.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react';

export function BeerCan(props) {

  const { nodes, materials } = useGLTF('/beercannew.glb')
  const canRef = useRef(null)

  useGSAP(() => {
    // gsap.from(canRef.current.position, { y: 10, duration: 1.5, immediateRender: false, delay: 0.01 })
    // gsap.from(canRef.current.rotation, { y: -10, duration: 1.5 });
    gsap.from(canRef.current.rotation, { x: 5, duration: 1.5 })
  }, [])

  return (
    <group ref={canRef} position={[-0.829, 4.1, -4.274]} rotation={[-0.1, 1.5, 0]} scale={[1.11, 2.0, 1.11]}>
      <mesh geometry={nodes.Cylinder_1.geometry} material={materials['top of can']} />
      <mesh geometry={nodes.Cylinder_2.geometry} material={materials.image} />
    </group>
  )
}

useGLTF.preload('/beercannew.glb')
